require 'rubygems'
require 'rstack'
require 'rstack/configuration'
require File.join(File.dirname(__FILE__), 'lib', '#{pathized_project_name}', 'version')

RStack::Configuration.new '#{project_name}' do |config|
  config.summary  = '[ENTER A SUMMARY]'
  config.author   = '#{author}'
  config.email    = '[ENTER YOUR EMAIL]'
  config.url      = ''
  config.version  = #{module_name}::Version::STRING
end
